// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeEngine(Path string) *gin.Engine {
	config := InitialConf(Path)
	db := InitialDB(config)
	engine := InitialEngine(db, config)
	return engine
}

func InitializeRouteGroup(Path string) gin.RouterGroup {
	config := InitialConf(Path)
	db := InitialDB(config)
	routerGroup := InitialRoutes(db, config)
	return routerGroup
}
